project_id = "ttoyhiyjlocjofpwzkoz"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-client]
    verify_jwt = true
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-transactional-email]
    verify_jwt = true
  [functions.analyze-website]
    verify_jwt = false
  [functions.analyze-speed]
    verify_jwt = false
